import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Card } from "@/components/ui/card";
import Section from '@/components/resume/blocks/Section';
import TimelineItem from '@/components/resume/blocks/TimelineItem';
import Tag from '@/components/resume/blocks/Tag';
export default function MainContent() {
    return (_jsxs("main", { className: "space-y-6", children: [_jsx(Card, { tone: "default", children: _jsx(Section, { title: "About", subtitle: _jsx(_Fragment, { children: "Platform/DevOps engineer focused on secure identity, automation, and reliable delivery. I build boring systems that don\u2019t fail at 2AM: CI/CD that\u2019s predictable, access that\u2019s auditable, and platforms that are easy to operate." }), children: _jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsx(Tag, { tone: "accent", children: "Platform Engineering" }), _jsx(Tag, { children: "DevSecOps" }), _jsx(Tag, { children: "Okta / IAM" }), _jsx(Tag, { children: "Kubernetes" })] }) }) }), _jsx(Card, { tone: "default", children: _jsx(Section, { title: "Experience", children: _jsxs("div", { className: "space-y-6", children: [_jsx(TimelineItem, { title: "Platform Engineer", org: "Army Software Factory", range: "2023\u2013Present", location: "Austin, TX", summary: _jsx(_Fragment, { children: "Own platform operations and identity workflows across developer tooling. Build repeatable onboarding and access patterns, tighten security controls, and document everything so teams move faster without breaking compliance." }), bullets: [
                                    'Automated onboarding + access validation across Okta, GitLab, and Google Workspace.',
                                    'Implemented CI/CD quality gates (lint/test/coverage) with cleaner logs and traceable artifacts.',
                                    'Standardized incident triage with runbooks, escalation paths, and audit-friendly checklists.',
                                ], tags: ['Okta', 'GitLab', 'Google Workspace', 'CI/CD'] }), _jsx(TimelineItem, { title: "(Your previous role)", org: "(Org)", range: "(Dates)", location: "(Location)", bullets: [
                                    'Add 2–3 impact bullets. Use numbers where possible: time saved, incidents reduced, users supported.',
                                    'Keep bullets “did X → resulted in Y”. Avoid job-description fluff.',
                                ], tags: ['Systems', 'Security', 'Automation'] })] }) }) }), _jsx(Card, { tone: "default", interactive: true, children: _jsx(Section, { title: "Projects", subtitle: "Selected work that demonstrates platform thinking, automation, and operational reliability.", children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "rounded-xl border border-zinc-800/70 bg-zinc-950/40 p-4 print:bg-white", children: [_jsxs("div", { className: "flex flex-wrap items-baseline justify-between gap-3", children: [_jsx("h3", { className: "font-semibold text-zinc-100 print:text-zinc-900", children: "TechOps Portal" }), _jsx("span", { className: "text-xs text-zinc-400 print:text-zinc-600", children: "Internal tooling / documentation" })] }), _jsx("p", { className: "mt-2 text-sm text-zinc-200 print:text-zinc-700", children: "Built a centralized portal for onboarding, SOPs, and ticket triage so teams can execute consistent processes fast." }), _jsxs("div", { className: "mt-3 flex flex-wrap gap-2", children: [_jsx(Tag, { children: "Docs" }), _jsx(Tag, { children: "Automation" }), _jsx(Tag, { tone: "accent", children: "Platform" })] })] }), _jsxs("div", { className: "rounded-xl border border-zinc-800/70 bg-zinc-950/40 p-4 print:bg-white", children: [_jsxs("div", { className: "flex flex-wrap items-baseline justify-between gap-3", children: [_jsx("h3", { className: "font-semibold text-zinc-100 print:text-zinc-900", children: "CI/CD Deploy to cPanel via SSH" }), _jsx("span", { className: "text-xs text-zinc-400 print:text-zinc-600", children: "GitHub Actions pipeline" })] }), _jsx("p", { className: "mt-2 text-sm text-zinc-200 print:text-zinc-700", children: "Implemented build/test/deploy stages with predictable outputs and secure secrets handling." }), _jsxs("div", { className: "mt-3 flex flex-wrap gap-2", children: [_jsx(Tag, { children: "GitHub Actions" }), _jsx(Tag, { children: "SSH" }), _jsx(Tag, { tone: "accent", children: "CI/CD" })] })] })] }) }) }), _jsx(Card, { tone: "subtle", children: _jsx(Section, { title: "Education", children: _jsxs("div", { className: "text-sm text-zinc-200 print:text-zinc-700", children: [_jsxs("div", { className: "flex flex-wrap items-baseline justify-between gap-3", children: [_jsx("span", { className: "font-medium text-zinc-100 print:text-zinc-900", children: "(Degree) \u2014 (School)" }), _jsx("span", { className: "text-xs text-zinc-400 print:text-zinc-600", children: "(Year)" })] }), _jsx("p", { className: "mt-1 text-zinc-300 print:text-zinc-700", children: "(Optional: relevant coursework / honors)" })] }) }) })] }));
}
